### PR TITLE
Fixed indent alfter list

### PR DESCRIPTION
**Pull request by hori-ryota**

### CODE REVIEW

**Comment by rcmdnk** [comment]
Thanks, that's fine with me.

**Comment by hori-ryota** [comment]
Thanks. By the way, how about this?

[Fixed indent of list by hori-ryota · Pull Request #218 · plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown/pull/218/files)

**Comment by rcmdnk** [comment]
For numbering bullets, I agree.

For indent function, maybe we can make it much simpler, like:

```vim
" Only define the function once
if exists("*GetMkdIndent") | finish | endif

function GetMkdIndent()
  let lnum = prevnonblank(v:lnum - 1)
  if lnum == 0 || v:lnum - lnum > 2
    return 0
  endif
  return indent(lnum)
endfunction
```

I think it works as same as your modification, doesn't it?

In addition, I prefer to do:

```vim
  if lnum == 0 || v:lnum - lnum > 1
```

For syntax, it is better to do:

```vim
setlocal comments+=bn:>
```

Ho do you think?

**Comment by hori-ryota** [comment]
Thanks.

`needs_keeping` needs to be recursive.

e.g.

```
* list item

    first paragraph

    second paragraph
```

is

---
* list item

    first paragraph

    second paragraph

---

But this method incomplete in terms of ignoring line feeds.

`setlocal comments+=bn:>` is nice!

**Comment by rcmdnk** [comment]
ok, I got what you want. (sorry, I didn't think the third condition is actually intended...)

I think it is better to have current your pull request's one,
because your another pull request doesn't work when

```
* list item
second line

    first paragraph

    second paragraph
```

`first paragraph` is not indented.

With original one, `second line` is also indented, and paragraphs are also indented.

In case you don't have `second line`, you can immediately finish the indent after a blank line with your new one, though.

But the behavior such 

```
* item list<cursor1>
<cursor2>
    <cursor3>
<cursor4>
```

is a bit annoying if you actually finish the item (and it happens much more than the cases with paragraphs.)


By the way, I found the typo in line 54 of your pull request (`s:is_li_stat` -> `s:is_li_start`).

**Comment by hori-ryota** [comment]
> By the way, I found the typo in line 54 of your pull request (s:is_li_stat -> s:is_li_start).

Thanks, I updated.


I also think so the behavior, but using numbering bullet indented when new line added.

e.g.

```
1. numbered<CR>
    <here>
```

If that's the case, I think better <cursor3> also behave not indented.

**Comment by rcmdnk** [comment]
How about this?

    setlocal comments=b:*,b:+,b:-,b:1.

in syntax/markdown.vim.

It works for:

    1. aaa
    1. bbb
    1. ccc
    1. 

Though it is more complex if you want to increment here,
Markdown parser automatically increments the number and more frexible to change lines.

**Pull request merged**
